
apiVersion: v1
kind: Namespace
metadata:
  name: static

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-static
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 663461323242.dkr.ecr.us-east-2.amazonaws.com/k8s-static:$BUILD_NUMBER
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-static-svc
  namespace: static
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ingress
 namespace: static
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: static.sulthana.xyz
   http:
     paths:
     - path:
       backend:
         serviceName: k8s-static-svc
         servicePort: 80


